import type { EndpointRuntimeInventory, RuntimeEndpoint, RuntimeEndpointConnectionState, RuntimeEndpointRef, RuntimeEndpoints, RuntimeInventory } from './types'
const ID=/^[0-9a-f]{32}$/
const STATES=new Set<RuntimeEndpointConnectionState>(['reachable','disabled','authentication_required','unreachable','incompatible','unknown'])
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
const text=(v:unknown)=>typeof v==='string'&&v.length>0&&new TextEncoder().encode(v).length<=128&&![...v].some(c=>/[\u0000-\u001f\u007f]/.test(c))
export const isStableMachineId=(v:string)=>ID.test(v)
export const endpointKey=(v:RuntimeEndpointRef)=>v.kind==='local'?'local':`machine:${v.machine_id}`
function ref(v:unknown):RuntimeEndpointRef { if(!record(v)) throw Error('Invalid endpoint identity'); if(v.kind==='local') return {kind:'local'}; if(v.kind==='machine'&&typeof v.machine_id==='string'&&ID.test(v.machine_id)) return {kind:'machine',machine_id:v.machine_id}; throw Error('Invalid endpoint identity') }
function endpoint(v:unknown):RuntimeEndpoint { if(!record(v)||!text(v.label)||typeof v.enabled!=='boolean'||typeof v.connection_state!=='string'||!STATES.has(v.connection_state as RuntimeEndpointConnectionState)||!record(v.capabilities)||typeof v.capabilities.inventory_read!=='boolean'||typeof v.capabilities.mutations!=='boolean'||typeof v.capabilities.terminal_streaming!=='boolean'||!Array.isArray(v.sessions)||v.sessions.length>64) throw Error('Invalid endpoint'); const sessions=v.sessions.map(x=>{if(!record(x)||!text(x.name)||typeof x.is_default!=='boolean'||!(typeof x.observed_running==='boolean'||x.observed_running===null)) throw Error('Invalid session'); return {name:x.name as string,is_default:x.is_default,observed_running:x.observed_running}}); return {endpoint:ref(v.endpoint),label:v.label as string,enabled:v.enabled,connection_state:v.connection_state as RuntimeEndpointConnectionState,capabilities:v.capabilities as unknown as RuntimeEndpoint['capabilities'],sessions} }
export function parseRuntimeEndpoints(v:unknown):RuntimeEndpoints { if(!record(v)||v.adapter!=='herdr'||!Array.isArray(v.endpoints)||v.endpoints.length>65) throw Error('Invalid Herdr endpoint response'); const endpoints=v.endpoints.map(endpoint), keys=endpoints.map(x=>endpointKey(x.endpoint)); if(new Set(keys).size!==keys.length||keys.filter(x=>x==='local').length!==1) throw Error('Invalid endpoint identities'); return {adapter:'herdr',endpoints} }
function inventory(v:unknown):RuntimeInventory { if(!record(v)||v.adapter!=='herdr'||!text(v.session)||!record(v.focus)||!Array.isArray(v.workspaces)||!Array.isArray(v.tabs)||!Array.isArray(v.panes)||!Array.isArray(v.workers)||!Array.isArray(v.child_agents)) throw Error('Invalid inventory'); return v as unknown as RuntimeInventory }
export function parseMachineInventory(v:unknown,id:string):EndpointRuntimeInventory { if(!ID.test(id)||!record(v)) throw Error('Invalid inventory'); const e=ref(v.endpoint); if(e.kind!=='machine'||e.machine_id!==id) throw Error('Remote inventory endpoint identity mismatch'); return {endpoint:e,inventory:inventory(v.inventory)} }
function valid(v:string,name:string,optional=false){if(optional&&!v)return;if(!v)throw Error(`${name} is required.`);if(v.includes('\0')||/[\r\n]/.test(v))throw Error(`${name} cannot contain newlines or NUL characters.`);if([...v].some(c=>/[\u0000-\u001f\u007f]/.test(c)))throw Error(`${name} cannot contain control characters.`)}
export const quotePosixArgument=(v:string)=>`'${v.replaceAll("'",`'"'"'`)}'`
export function buildAddMachineCommand({sshTarget,label,remoteSession}:{sshTarget:string;label:string;remoteSession:string}) { valid(sshTarget,'SSH target');valid(label,'Label',true);valid(remoteSession,'Remote session',true);return ['herdr machine add',label?`--label=${quotePosixArgument(label)}`:'',remoteSession?`--remote-session=${quotePosixArgument(remoteSession)}`:'','--',quotePosixArgument(sshTarget)].filter(Boolean).join(' ') }
export function buildReconnectCommand(id:string){if(!ID.test(id))throw Error('Reconnect requires a validated stable machine ID.');return `herdr machine reconnect ${quotePosixArgument(id)}`}
export function selectedEndpointAfterRefresh(key:string,endpoints:RuntimeEndpoint[]){return endpoints.some(x=>endpointKey(x.endpoint)===key)?key:'local'}
export const CONNECTION_LABELS:Record<RuntimeEndpointConnectionState,string>={reachable:'Connected',disabled:'Disabled',authentication_required:'Authentication required',unreachable:'Unreachable',incompatible:'Incompatible',unknown:'Connection unknown'}
